<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtHealthcare</name>
   <tag></tag>
   <elementGuidId>b6da1c59-a41f-4f5f-8b5b-506babb6927c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#program</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
